config/routes.rb
ObjectsOnRails::Application.routes.draw do
  get "posts/new"

  get "blog/index"

  resources :posts

  root :to => 'blog#index'
end

app/models/blog.rb
class Blog

  attr_reader :entries
  attr_writer :post_maker


  def initialize
    @entries = []
  end

  def title
    "Watching paint dry"
  end

  def subtitle
    "The trusted source for drying paint news & opinion"
  end

  def new_post(*args)
    post_maker.call(*args).tap do |p|
      p.blog = self
    end
  end

  def entries
    @entries.sort_by { |e| e.pubdate }.reverse.take(10)
  end

  def add_entry(entry)
    @entries << entry
  end

  private

  def post_maker
    @post_maker ||= Post.public_method(:new)
  end
end

app/models/post.rb
require 'active_model'

class Post
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :title, :body, :blog, :pubdate, :image_url

  validates :title, :presence => true

  def initialize(attrs ={})
    attrs.each { |k,v| send("#{k}=", v) }

  end

  def publish(clock = DateTime)
    return false unless valid?
    blog.pubdate = clock.now
    blog.add_entry(self)
    return true
  end

  def persisted?
    false
  end

  def picture?
    image_url.present?
  end

  def self.first_before(date)
    first(conditions: ["pubdate < ?", date],
          order:      "pubdate DESC")
  end

  def self.first_after(date)
    first(conditions: ["pubdate > ?", date],
          order:      "pubdate ASC")
  end

  def prev
    self.class.first_before(pubdate)
  end

  def next
    self.class.first_after(pubdate)
  end

  def up
    THE_BLOG
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :init_blog

  helper :exhibits

  private

  def init_blog
    @blog = THE_BLOG
  end

  def url_for(*args)
    # use string matching to avoid dev-mode autoloading issues
    if args.size == 1 && args.first.class.name == 'Blog'
      root_url
    else
      super
    end
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :json

  include ExhibitsHelper 

  def new
    @post = @blog.new_post
  end

  def create
    @post = @blog.new_post(params[:post])
    if @post.publish
      redirect_to root_path, :notice => 'Post added!'
    else
      render 'new'
    end
  end

  def show
    @post = exhibit(Post.find_by_id(params[:id]), self)
    respond_with @post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
  def exhibit(model, context)
    case model.class.name
    when 'Post'
      if model.picture?
        ::PicturePostExhibit.new(model,context)
      else
        ::TextPostExhibit.new(model, context)
      end
    else
      model
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/_entry.html.erb
<% entry = exhibit(entry, self) %>
<article>
  <header>
    <p>
      <time pubdate="pubdate"><%= entry.pubdate %></time>
    </p>
    <h3><%= entry.title %></h3>
  </header>
  <p><%= entry.render_body %></p>
</article>

app/views/blog/index.html.erb
<h1>Blog#index</h1>
<p>Find me in app/views/blog/index.html.erb</p>

<%= @blog.title %>
<%= @blog.subtitle %>

<%= render partial: "entry", collection: @blog.entries %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ObjectsOnRails</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="sidebar two columns">
    <nav>
      <ul>
        <li><%= link_to "New post...", new_post_path %></li>
      </ul>
    </nav>
  </div>

  <%= yield %>

</body>
</html>

app/views/posts/_picture_body.html.erb
<figure>
  <img src="<%= post.image_url %>" />
  <figcaption><%= post.body %></figcaption>
</figure>

app/views/posts/new.html.erb
<h1>Posts#new</h1>

<%= form_for @post do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :body %>
  <%= label :image_url, "Picture URL:" %>
  <%= f.text_field :image_url %>
  <%= f.submit %>
<% end %>